name: Docker Image CI

on:
  push:
    branches: ['staging']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build -t vaibhavrajnathchauhan/sports-academy-backend-production:${{ github.run_number }} .
      - name: Pushing docker images
        run: |
          docker login -u ${{secrets.DOCKER_HUB_USER}} -p ${{secrets.DOCKER_HUB_PASSWORD}}
          docker push vaibhavrajnathchauhan/sports-academy-backend-production:${{ github.run_number }}
      - name: Recreating docker container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP_1 }}
          username: ec2-user
          key: ${{secrets.SERVER_KEY}}
          script: |
            cd sports-academy/production
            BE_TAG=${{ github.run_number }} docker-compose up -d

      - name: Recreating docker container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP_2 }}
          username: ec2-user
          key: ${{secrets.SERVER_KEY}}
          script: |
            cd sports-academy/production
            BE_TAG=${{ github.run_number }} docker-compose up -d
